/motors/<alias>
/motor/<motor>/get/<register>
/motors/get/positions
/motors/alias
/motors/<motors>/get/<register>
/motors/set/goto/<motors_position_duration>
/motors/set/registers/<motors_register_value>
/motors/set/positions/<positions>
/motor/<motor>/set/<register>/<value>
/motor/<motor>/goto/<position>/<duration>
/snap-blocks.xml
/snap/<project>
/ip/<host>
/ip/
/reset-simulation
/primitives
/primitives/running
/primitive/<primitive>/start
/primitive/<primitive>/stop
/primitive/<primitive>/pause
/primitive/<primitive>/resume
/primitive/<primitive>/properties
/primitive/<primitive>/get/<property>
/primitive/<primitive>/set/<property>/<value>
/primitive/<primitive>/methodes
/primitive/<primitive>/call/<method>
/primitive/<primitive>/call/<method>/<args>
/primitive/MoveRecorder/<move_name>/start
/primitive/MoveRecorder/<move_name>/stop
/primitive/MoveRecorder/<move_name>/attach/<motors>
/primitive/MoveRecorder/<move_name>/get_motors
/primitive/MoveRecorder/<move_name>/start/<motors>
/primitive/MoveRecorder/<move_name>/remove
/primitive/MoveRecorder
/primitive/MovePlayer
/primitive/MovePlayer/<move_name>/start
/primitive/MovePlayer/<move_name>/start/<move_speed>
/primitive/MovePlayer/<move_name>/start/<move_speed>/backwards
/primitive/MovePlayer/<move_name>/stop
/detect/<marker>
/ik/<chain>/endeffector
/ik/<chain>/goto/<x>/<y>/<z>/<duration>
